// <auto-generated />
using System;
using Backend.Veteriner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Veteriner.Infrastructure.Persistence.Migrations.Query
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20260620000207_AddPetReadModel")]
    partial class AddPetReadModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.AppointmentReadModel", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientPhoneNormalized")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PetBreed")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PetBreedRefName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClientId");

                    b.HasIndex("TenantId", "PetId")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_PetId");

                    b.HasIndex("TenantId", "ClinicId", "ScheduledAtUtc", "AppointmentId")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClinicId_ScheduledAtUtc_AppointmentId");

                    b.HasIndex("TenantId", "ClinicId", "Status", "ScheduledAtUtc")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClinicId_Status_ScheduledAtUtc");

                    b.ToTable("AppointmentReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClientReadModel", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEventOccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNormalized")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClientId");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_ClientReadModels_TenantId_Email");

                    b.HasIndex("TenantId", "PhoneNormalized")
                        .HasDatabaseName("IX_ClientReadModels_TenantId_PhoneNormalized");

                    b.HasIndex("TenantId", "FullNameNormalized", "ClientId")
                        .HasDatabaseName("IX_ClientReadModels_TenantId_FullNameNormalized_ClientId");

                    b.ToTable("ClientReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicClientActivityReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastAppointmentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "ClinicId", "ClientId");

                    b.HasIndex("TenantId", "ClinicId", "LastAppointmentAtUtc", "ClientId")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_ClinicClientActivityReadModels_TenantId_ClinicId_LastAppointmentAtUtc_ClientId");

                    b.ToTable("ClinicClientActivityReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicDailyAppointmentStatsReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduledCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "ClinicId", "LocalDate");

                    b.ToTable("ClinicDailyAppointmentStatsReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicPetActivityReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastAppointmentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "ClinicId", "PetId");

                    b.HasIndex("TenantId", "ClinicId", "LastAppointmentAtUtc", "PetId")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_ClinicPetActivityReadModels_TenantId_ClinicId_LastAppointmentAtUtc_PetId");

                    b.ToTable("ClinicPetActivityReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.PetReadModel", b =>
                {
                    b.Property<Guid>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Breed")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("BreedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BreedRefName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientFullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientFullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ColorNameNormalized")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEventOccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpeciesNameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("PetId");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("IX_PetReadModels_TenantId_ClientId");

                    b.HasIndex("TenantId", "ColorId")
                        .HasDatabaseName("IX_PetReadModels_TenantId_ColorId");

                    b.HasIndex("TenantId", "SpeciesId")
                        .HasDatabaseName("IX_PetReadModels_TenantId_SpeciesId");

                    b.HasIndex("TenantId", "ClientFullNameNormalized", "PetId")
                        .HasDatabaseName("IX_PetReadModels_TenantId_ClientFullNameNormalized_PetId");

                    b.HasIndex("TenantId", "NameNormalized", "PetId")
                        .HasDatabaseName("IX_PetReadModels_TenantId_NameNormalized_PetId");

                    b.ToTable("PetReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ProcessedProjectionEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId", "ConsumerName");

                    b.ToTable("ProcessedProjectionEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
