// <auto-generated />
using System;
using Backend.Veteriner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Veteriner.Infrastructure.Persistence.Migrations.Query
{
    [DbContext(typeof(QueryDbContext))]
    [Migration("20260616184445_InitialQueryReadModels")]
    partial class InitialQueryReadModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.AppointmentReadModel", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ScheduledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppointmentId");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClientId");

                    b.HasIndex("TenantId", "PetId")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_PetId");

                    b.HasIndex("TenantId", "ClinicId", "ScheduledAtUtc", "AppointmentId")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClinicId_ScheduledAtUtc_AppointmentId");

                    b.HasIndex("TenantId", "ClinicId", "Status", "ScheduledAtUtc")
                        .HasDatabaseName("IX_AppointmentReadModels_TenantId_ClinicId_Status_ScheduledAtUtc");

                    b.ToTable("AppointmentReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicClientActivityReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastAppointmentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "ClinicId", "ClientId");

                    b.HasIndex("TenantId", "ClinicId", "LastAppointmentAtUtc", "ClientId")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_ClinicClientActivityReadModels_TenantId_ClinicId_LastAppointmentAtUtc_ClientId");

                    b.ToTable("ClinicClientActivityReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicDailyAppointmentStatsReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduledCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "ClinicId", "LocalDate");

                    b.ToTable("ClinicDailyAppointmentStatsReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ClinicPetActivityReadModel", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastAppointmentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastProjectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "ClinicId", "PetId");

                    b.HasIndex("TenantId", "ClinicId", "LastAppointmentAtUtc", "PetId")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_ClinicPetActivityReadModels_TenantId_ClinicId_LastAppointmentAtUtc_PetId");

                    b.ToTable("ClinicPetActivityReadModels", (string)null);
                });

            modelBuilder.Entity("Backend.Veteriner.Infrastructure.Persistence.Query.Models.ProcessedProjectionEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId", "ConsumerName");

                    b.ToTable("ProcessedProjectionEvents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
